/*
 * File: app/view/servicio/Panel.js
 *
 * This file was generated by Sencha Architect version 2.1.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.1.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.1.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('App.view.servicio.Panel', {
    extend: 'Ext.panel.Panel',
    alias: 'widget.serviciopanel',

    border: '',
    padding: '',
    style: 'border:0',
    ui: 'default-framed',
    width: 950,
    bodyBorder: true,
    title: '',

    initComponent: function() {
        var me = this;

        Ext.applyIf(me, {
            dockedItems: [
                {
                    xtype: 'toolbar',
                    name: 'MainToolbar',
                    dock: 'top',
                    margin: 2,
                    style: 'border:0;padding:0;',
                    layout: {
                        padding: 4,
                        type: 'hbox'
                    },
                    items: [
                        {
                            xtype: 'button',
                            action: 'new',
                            iconCls: 'new_document',
                            tooltip: 'Crear nuevo cliente'
                        },
                        {
                            xtype: 'textfield',
                            width: 300,
                            name: 'FindServicio',
                            fieldLabel: '',
                            hideLabel: true,
                            emptyText: 'NombreServicio'
                        },
                        {
                            xtype: 'button',
                            action: 'find',
                            iconCls: 'open_document',
                            tooltip: 'Buscar cliente por Nit o Nombre'
                        },
                        {
                            xtype: 'button',
                            action: 'save',
                            iconCls: 'save_document',
                            tooltip: 'Guardar cambios'
                        },
                        {
                            xtype: 'button',
                            action: 'remove',
                            iconCls: 'remove',
                            tooltip: 'Borrar Cliente'
                        }
                    ]
                }
            ],
            items: [
                {
                    xtype: 'form',
                    fieldDefaults: {
                        msgTarget: 'side',
                        labelWidth: 80,
                        labelAlign: 'right'
                    },
                    name: 'ServicioForm',
                    margin: 10,
                    padding: 5,
                    ui: 'default-framed',
                    bodyBorder: false,
                    bodyPadding: '10 50 10 50',
                    title: '',
                    items: [
                        {
                            xtype: 'hiddenfield',
                            name: 'Id',
                            fieldLabel: 'Nit'
                        },
                        {
                            xtype: 'textfield',
                            anchor: '100%',
                            name: 'Nombre',
                            fieldLabel: 'Nombre',
                            allowBlank: false,
                            enforceMaxLength: true,
                            maxLength: 128,
                            maxLengthText: 'The maximum length for this field is {128}'
                        },
                        {
                            xtype: 'checkboxfield',
                            anchor: '100%',
                            name: 'Activo',
                            fieldLabel: 'Activo',
                            hideLabel: false,
                            boxLabel: ''
                        }
                    ]
                },
                {
                    xtype: 'panel',
                    margin: 10,
                    ui: 'default-framed',
                    layout: {
                        align: 'stretch',
                        padding: 5,
                        type: 'hbox'
                    },
                    animCollapse: false,
                    collapsible: true,
                    title: 'Procedimientos',
                    items: [
                        {
                            xtype: 'gridpanel',
                            name: 'ServicioProcedimientoList',
                            flex: 1,
                            margin: 5,
                            ui: 'default-framed',
							store: 'ServicioProcedimiento',
                            columns: [
                                {
                                    xtype: 'gridcolumn',
                                    draggable: false,
                                    resizable: false,
                                    sortable: false,
                                    dataIndex: 'NombreProcedimiento',
                                    flex: 1,
                                    hideable: false,
                                    text: 'Procedimiento'
                                }
                            ]
                        },
                        {
                            xtype: 'form',
                            name: 'ServicioProcedimientoForm',
                            fieldDefaults: {
                                msgTarget: 'side',
                                labelWidth: 80,
                                labelAlign: 'right'
                            },
                            flex: 1,
                            border: 0,
                            margin: 5,
                            style: 'border:0;padding:0;',
                            ui: 'default-framed',
                            width: 325,
                            bodyPadding: 10,
                            title: '',
                            dockedItems: [
                                {
                                    xtype: 'toolbar',
                                    name: 'ServicioProcedimientoToolbar',
                                    dock: 'top',
                                    border: '',
                                    items: [
                                        {
                                            xtype: 'button',
                                            action: 'new',
                                            iconCls: 'add',
                                            tooltip: 'agregar procedimiento'
                                        },
                                        {
                                            xtype: 'button',
                                            action: 'remove',
                                            iconCls: 'remove',
                                            tooltip: 'borrar contacto'
                                        }
                                    ]
                                }
                            ],
                            items: [
                                {
                                    xtype: 'textfield',
                                    anchor: '100%',
                                    name: 'NombreProcedimiento',
                                    fieldLabel: 'Nombre',
                                    allowBlank: false
                                },
                                {
                                    xtype: 'textareafield',
                                    anchor: '100%',
                                    name: 'DescripcionProcedimiento',
                                    fieldLabel: 'Descripcion',
                                    allowBlank: false
                                },
                                {
                                    xtype: 'textfield',
                                    anchor: '100%',
                                    name: 'ValorBaseProcedimiento',
                                    fieldLabel: 'Valor Base'
                                },
                                {
                                    xtype: 'textfield',
                                    anchor: '100%',
                                    name: 'PorcentajeIvaProcedimiento',
                                    fieldLabel: 'Iva %'
                                },
                                {
                                    xtype: 'textfield',
                                    anchor: '100%',
                                    name: 'ValorIvaProcedimiento',
                                    fieldLabel: 'Iva $'
                                },
                                {
                                    xtype: 'textfield',
                                    anchor: '100%',
                                    name: 'ValorUnitarioProcedimiento',
                                    fieldLabel: 'Total'
                                },
                                {
                                    xtype: 'checkboxfield',
                                    anchor: '100%',
                                    name: 'ActivoProcedimiento',
                                    fieldLabel: 'Activo',
                                    boxLabel: ''
                                },
                                {
                                    xtype: 'hiddenfield',
                                    name: 'Id',
                                    fieldLabel: 'Label'
                                },
                                {
                                    xtype: 'hiddenfield',
                                    name: 'IdServicio',
                                    fieldLabel: 'Label'
                                },
                                {
                                    xtype: 'hiddenfield',
                                    name: 'IdProcedimiento',
                                    fieldLabel: 'Label'
                                }
                            ]
                        }
                    ]
                }
            ]
        });

        me.callParent(arguments);
    }

});
