/*
 * File: app/controller/Consecutivo.js
 *
 * This file was generated by Sencha Architect version 2.1.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.1.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.1.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('App.controller.Consecutivo', {
    extend: 'Ext.app.Controller',

    views: [
        'consecutivo.Panel'
    ],

    refs: [
        {
            ref: 'consecutivoForm',
            selector: 'form[name=ConsecutivoForm]'
        }
    ],

    onConsecutivoSaveButtonClick: function(button, e, options) {
        var form = this.getConsecutivoForm().getForm();
        var record= form.getFieldValues(false);
        Aicl.Util.executeRestRequest({
            url : Aicl.Util.getUrlApi()+'/Consecutivo/'+ (record.Id?'update/'+record.Id:'create'),
            method : record.Id?'put':'post',
            params: record,
            success : function(result){
                if(result.Data.length){
                    form.setValues(result.Data[0]);
                }
                Aicl.Util.msg('OK', (record.Id?'Consecutivo Actualizado':'Consecutivo Creado'));
            },        
            failure : function(response, options){
                Ext.Msg.alert('Error', 'Error al guardar datos del Consecutivo. Intente mas tarde');
            }
        });
    },

    onLaunch: function() {
        var form = this.getConsecutivoForm().getForm();
        Aicl.Util.executeRestRequest({
            url : Aicl.Util.getUrlApi()+'/Consecutivo/read',
            method : 'get',
            success : function(result){
                if(result.Data.length){
                    form.setValues(result.Data[0]);
                    Aicl.Util.msg('OK','Datos Cargados');
                }
                else{
                    Aicl.Util.msg('OK','Se creara el consecutivo');
                }
            },
            failure : function(response, options){
                Ext.Msg.alert('Error', 'Error al cargar Consecutivo. Intente mas tarde');
            }

        });
    },

    init: function(application) {
        this.control({
            "toolbar[name=ConsecutivoToolbar] button[action=save]": {
                click: this.onConsecutivoSaveButtonClick
            }
        });
    }

});
