/*
 * File: app/view/consecutivo/Panel.js
 *
 * This file was generated by Sencha Architect version 2.1.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.1.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.1.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('App.view.consecutivo.Panel', {
    extend: 'Ext.panel.Panel',
    alias: 'widget.consecutivopanel',

    cls: 'form-noborder',
    height: 229,
    padding: 10,
    ui: 'default-framed',
    width: 412,
    bodyPadding: 20,
    frameHeader: false,
    title: '',

    initComponent: function() {
        var me = this;

        Ext.applyIf(me, {
            dockedItems: [
                {
                    xtype: 'toolbar',
                    name: 'ConsecutivoToolbar',
                    dock: 'top',
                    style: '{\n    border:0;\n}',
                    items: [
                        {
                            xtype: 'button',
                            action: 'save',
                            iconCls: 'save_document',
                            text: ''
                        }
                    ]
                }
            ],
            items: [
                {
                    xtype: 'form',
                    fieldDefaults: {
                        msgTarget: 'side',
                        labelWidth: 120,
                        labelAlign: 'right'
                    },
                    name: 'ConsecutivoForm',
                    cls: 'form-border',
                    padding: 30,
                    ui: 'default-framed',
                    width: 350,
                    bodyPadding: 20,
                    title: '',
                    items: [
                        {
                            xtype: 'numberfield',
                            anchor: '100%',
                            width: 290,
                            name: 'Valor',
                            value: 0,
                            fieldLabel: 'Ultimo Consecutivo',
                            allowBlank: false,
                            allowDecimals: false
                        },
                        {
                            xtype: 'hiddenfield',
                            anchor: '100%',
                            name: 'Id',
                            fieldLabel: 'Label'
                        },
                        {
                            xtype: 'hiddenfield',
                            anchor: '100%',
                            name: 'Documento',
                            fieldLabel: 'Label'
                        },
                        {
                            xtype: 'hiddenfield',
                            anchor: '100%',
                            name: 'Prefijo',
                            fieldLabel: 'Label'
                        }
                    ]
                }
            ]
        });

        me.callParent(arguments);
    }

});