/*
 * File: app/view/empresa/Form.js
 *
 * This file was generated by Sencha Architect version 2.1.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.1.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.1.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('App.view.empresa.Form', {
    extend: 'Ext.form.Panel',
    alias: 'widget.empresaform',

    name: 'EmpresaForm',
    cls: 'form-border',
    frame: true,
    height: 491,
    margin: '10 10 10 10',
    width: 633,
    bodyPadding: 5,
    title: '',

    initComponent: function() {
        var me = this;

        Ext.applyIf(me, {
            fieldDefaults: {
                msgTarget: 'side',
                labelWidth: 120,
                labelAlign: 'right'
            },
            dockedItems: [
                {
                    xtype: 'toolbar',
                    name: 'EmpresaToolbar',
                    dock: 'top',
                    style: '{\n    border:0px;\n    \n}',
                    items: [
                        {
                            xtype: 'button',
                            action: 'save',
                            iconCls: 'save_document',
                            text: ''
                        }
                    ]
                }
            ],
            items: [
                {
                    xtype: 'tabpanel',
                    height: 444,
                    padding: '10 10 10 10',
                    width: 616,
                    bodyPadding: 20,
                    activeTab: 0,
                    items: [
                        {
                            xtype: 'panel',
                            height: 413,
                            autoScroll: true,
                            defaults: {
                                width: 450
                            },
                            title: 'Empresa',
                            items: [
                                {
                                    xtype: 'hiddenfield',
                                    name: 'Id',
                                    fieldLabel: 'Label'
                                },
                                {
                                    xtype: 'textfield',
                                    name: 'Nit',
                                    fieldLabel: 'Nit',
                                    allowBlank: false,
                                    enforceMaxLength: true,
                                    maxLength: 16,
                                    maxLengthText: 'Maximo {16} caracteres'
                                },
                                {
                                    xtype: 'textfield',
                                    name: 'Nombre',
                                    fieldLabel: 'Nombre',
                                    allowBlank: false,
                                    enforceMaxLength: true,
                                    maxLength: 64,
                                    maxLengthText: 'Maximo 64 Caracteres'
                                },
                                {
                                    xtype: 'textfield',
                                    name: 'Alias',
                                    fieldLabel: 'Alias',
                                    allowBlank: false,
                                    enforceMaxLength: true,
                                    maxLength: 64,
                                    maxLengthText: 'Maximo 64 Caracteres'
                                },
                                {
                                    xtype: 'textfield',
                                    name: 'Lema',
                                    fieldLabel: 'Lema',
                                    enforceMaxLength: true,
                                    maxLength: 64,
                                    maxLengthText: 'Maximo 64 Caracteres'
                                },
                                {
                                    xtype: 'textfield',
                                    name: 'Direccion',
                                    fieldLabel: 'Direccion',
                                    allowBlank: false,
                                    enforceMaxLength: true,
                                    maxLength: 128,
                                    maxLengthText: 'Maximo 128 Caracteres'
                                },
                                {
                                    xtype: 'textfield',
                                    name: 'Ciudad',
                                    fieldLabel: 'Ciudad',
                                    allowBlank: false,
                                    enforceMaxLength: true,
                                    maxLength: 32,
                                    maxLengthText: 'Maximo 32 Caracteres'
                                },
                                {
                                    xtype: 'textfield',
                                    name: 'Pais',
                                    fieldLabel: 'Pais',
                                    allowBlank: false,
                                    enforceMaxLength: true,
                                    maxLength: 32,
                                    maxLengthText: 'Maximo 32 Caracteres'
                                },
                                {
                                    xtype: 'textfield',
                                    name: 'Telefono',
                                    fieldLabel: 'Telefono',
                                    allowBlank: false,
                                    enforceMaxLength: true,
                                    maxLength: 32,
                                    maxLengthText: 'Maximo 32 Caracteres'
                                },
                                {
                                    xtype: 'textfield',
                                    name: 'Fax',
                                    fieldLabel: 'Fax',
                                    allowBlank: false,
                                    enforceMaxLength: true,
                                    maxLength: 16,
                                    maxLengthText: 'Maximo 16 Caracteres'
                                },
                                {
                                    xtype: 'textfield',
                                    name: 'Mail',
                                    fieldLabel: 'Mail',
                                    enforceMaxLength: true,
                                    maxLength: 128,
                                    maxLengthText: 'Maximo 128 Caracteres',
                                    vtype: 'email'
                                },
                                {
                                    xtype: 'textfield',
                                    name: 'Web',
                                    fieldLabel: 'Direccion Web',
                                    enforceMaxLength: true,
                                    maxLength: 64,
                                    maxLengthText: 'Maximo 64 Caracteres'
                                },
                                {
                                    xtype: 'textfield',
                                    name: 'CuentaBancaria',
                                    fieldLabel: 'Cuenta Bancaria',
                                    enforceMaxLength: true,
                                    maxLength: 128,
                                    maxLengthText: 'Maximo 128 Caracteres'
                                },
                                {
                                    xtype: 'textfield',
                                    name: 'DireccionAntigua',
                                    fieldLabel: 'Direccion Antigua',
                                    enforceMaxLength: true,
                                    maxLength: 128,
                                    maxLengthText: 'Maximo 128 Caracteres'
                                }
                            ]
                        },
                        {
                            xtype: 'panel',
                            defaults: {
                                width: 450
                            },
                            title: 'Responsable Ofertas',
                            items: [
                                {
                                    xtype: 'textfield',
                                    name: 'ResponsableOfertasNombre',
                                    fieldLabel: 'Nombre',
                                    allowBlank: false,
                                    enforceMaxLength: true,
                                    maxLength: 64,
                                    maxLengthText: 'Maximo 64 Caracteres'
                                },
                                {
                                    xtype: 'textfield',
                                    name: 'ResponsableOfertasCargo',
                                    fieldLabel: 'Cargo',
                                    allowBlank: false,
                                    enforceMaxLength: true,
                                    maxLength: 64,
                                    maxLengthText: 'Maximo 64 Caracteres'
                                },
                                {
                                    xtype: 'textfield',
                                    name: 'ResponsableOfertasCelular',
                                    fieldLabel: 'Celular',
                                    allowBlank: false,
                                    enforceMaxLength: true,
                                    maxLength: 16,
                                    maxLengthText: 'Maximo 16 Caracteres'
                                },
                                {
                                    xtype: 'textfield',
                                    name: 'ResponsableOfertasMail',
                                    fieldLabel: 'Mail',
                                    allowBlank: false,
                                    enforceMaxLength: true,
                                    maxLength: 128,
                                    maxLengthText: 'Maximo 128 Caracteres',
                                    vtype: 'email'
                                }
                            ]
                        },
                        {
                            xtype: 'panel',
                            defaults: {
                                width: 450
                            },
                            title: 'Aplicacion',
                            items: [
                                {
                                    xtype: 'textfield',
                                    name: 'MailServerUrl',
                                    fieldLabel: 'MailServerUrl',
                                    allowBlank: false,
                                    enforceMaxLength: true,
                                    maxLength: 32,
                                    maxLengthText: 'Maximo 32 Caracteres'
                                },
                                {
                                    xtype: 'textfield',
                                    name: 'MailServerUser',
                                    fieldLabel: 'MailServerUser',
                                    allowBlank: false,
                                    enforceMaxLength: true,
                                    maxLength: 128,
                                    maxLengthText: 'Maximo 128 Caracteres'
                                },
                                {
                                    xtype: 'textfield',
                                    name: 'MailServerPassword',
                                    fieldLabel: 'MailServerPassword',
                                    allowBlank: false,
                                    enforceMaxLength: true,
                                    maxLength: 128,
                                    maxLengthText: 'Maximo 128 Caracteres'
                                },
                                {
                                    xtype: 'textfield',
                                    name: 'MailServerPort',
                                    fieldLabel: 'MailServerPort',
                                    allowBlank: false,
                                    enforceMaxLength: true,
                                    maxLength: 6,
                                    maxLengthText: 'Maximo 6 Caracteres'
                                },
                                {
                                    xtype: 'checkboxfield',
                                    name: 'MailServerEnableSsl',
                                    fieldLabel: 'MailServerEnableSsl',
                                    boxLabel: '',
                                    checked: true
                                },
                                {
                                    xtype: 'textfield',
                                    name: 'ApplicationHost',
                                    fieldLabel: 'ApplicationHost',
                                    allowBlank: false,
                                    enforceMaxLength: true,
                                    maxLength: 64,
                                    maxLengthText: 'Maximo 64 Caracteres'
                                },
                                {
                                    xtype: 'textfield',
                                    name: 'ApplicationMailBox',
                                    fieldLabel: 'ApplicationMailBox',
                                    allowBlank: false,
                                    enforceMaxLength: true,
                                    maxLength: 128,
                                    maxLengthText: 'Maximo 128 Caracteres',
                                    vtype: 'email'
                                }
                            ]
                        },
                        {
                            xtype: 'panel',
                            title: 'Otras Opciones',
                            items: [
                                {
                                    xtype: 'textfield',
                                    name: 'Formato',
                                    fieldLabel: 'Formato'
                                },
                                {
                                    xtype: 'textfield',
                                    name: 'Edicion',
                                    fieldLabel: 'Edicion'
                                },
                                {
                                    xtype: 'checkboxfield',
                                    name: 'CambiarPrecio',
                                    fieldLabel: 'Permitir Modificar Precio'
                                }
                            ]
                        }
                    ]
                }
            ]
        });

        me.callParent(arguments);
    }

});