/*
 * File: app/view/permission/Window.js
 *
 * This file was generated by Sencha Architect version 2.1.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.1.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.1.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('App.view.permission.Window', {
    extend: 'Ext.window.Window',
    alias: 'widget.permissionwindow',

    height: 620,
    width: 720,
    layout: {
        align: 'stretch',
        type: 'hbox'
    },
    closeAction: 'hide',
    title: 'Permisos',
    modal: true,

    initComponent: function() {
        var me = this;

        Ext.applyIf(me, {
            items: [
                {
                    xtype: 'gridpanel',
                    name: 'PermissionList',
                    flex: 1,
                    padding: '20 20 20 20',
                    autoScroll: true,
                    title: '',
                    sortableColumns: false,
                    store: 'AuthPermission',
                    dockedItems: [
                        {
                            xtype: 'toolbar',
                            name: 'SelectPermissionToolbar',
                            dock: 'top',
                            items: [
                                {
                                    xtype: 'button',
                                    action: 'select',
                                    iconCls: 'select',
                                    text: 'Seleccionar'
                                }
                            ]
                        },
                        {
                            xtype: 'pagingtoolbar',
                            dock: 'bottom',
                            width: 360,
                            afterPageText: 'de {0}',
                            beforePageText: 'Pag',
                            displayInfo: false,
                            displayMsg: 'Mostrando {0} - {1} de {2}',
                            emptyMsg: 'Sin datos para mostrar',
                            firstText: 'Primera',
                            lastText: 'Ultima',
                            nextText: 'Siguiente',
                            prevText: 'Anterior',
                            refreshText: 'Refrescar',
                            store: 'AuthPermission'
                        }
                    ],
                    columns: [
                        {
                            xtype: 'gridcolumn',
                            sortable: false,
                            dataIndex: 'Name',
                            flex: 1,
                            text: 'Nombre'
                        }
                    ],
                    viewConfig: {

                    }
                },
                {
                    xtype: 'form',
                    name: 'PermissionForm',
                    fieldDefaults: {
                        msgTarget: 'side',
                        labelWidth: 80,
                        labelAlign: 'right'
                    },
                    flex: 1,
                    margins: '20 20 20 0',
                    cls: 'form-noborder',
                    padding: 5,
                    ui: 'default-framed',
                    bodyPadding: 20,
                    title: '',
                    dockedItems: [
                        {
                            xtype: 'toolbar',
                            name: 'PermissionToolbar',
                            dock: 'top',
                            style: '{\n    border:0;padding:0;\n}',
                            ui: 'default-framed',
                            items: [
                                {
                                    xtype: 'button',
                                    action: 'new',
                                    iconCls: 'new_document',
                                    text: ''
                                },
                                {
                                    xtype: 'button',
                                    action: 'save',
                                    iconCls: 'save_document',
                                    text: ''
                                },
                                {
                                    xtype: 'button',
                                    action: 'remove',
                                    iconCls: 'remove',
                                    text: ''
                                }
                            ]
                        }
                    ],
                    items: [
                        {
                            xtype: 'hiddenfield',
                            name: 'Id',
                            fieldLabel: 'Label'
                        },
                        {
                            xtype: 'textfield',
                            anchor: '100%',
                            name: 'Name',
                            fieldLabel: 'Nombre'
                        }
                    ]
                }
            ]
        });

        me.callParent(arguments);
    }

});